#!/bin/bash
#------------------------------------------------------------------------------
echo -e "\n
Start meshing
-------------------------------------------------------------------------------
"
echo -e "   - Remove 0 directory"
rm -r 0 >> logFile
rm -r constant/polymesh >> logFile
#rm -r system >> logFile
#rm -r postProcessing >> logFile

#------------------------------------------------------------------------------
echo -e "   - Create background mesh"
#gmsh -3 Wedge_smallTube.geo >> logFile
#cp -r ../basic_structure/constant constant
#cp -r ../basic_structure/system system

#gmshToFoam sphere_20k.msh >> logFile

#cp -r ../startup_files/constant constant
#cp -r ../startup_files/system system

gmshToFoam ss03_crit_coarse_1.msh >> logFile

#------------------------------------------------------------------------------
#echo -e "   - Corrections of names"
#sed 's/defaultFaces/back/g' constant/polyMesh/boundary -i

#------------------------------------------------------------------------------
#echo -e "   - Extrude one patch to make a 2D rotational mesh"
#extrudeMesh  >> logFile

#------------------------------------------------------------------------------
echo -e "   - Change boundary type (polyMesh/boundary)"
changeDictionary  >> logFile

#------------------------------------------------------------------------------
echo -e "   - Remove not needed patch entries"
createPatch -overwrite >> logFile


echo -e "\n
-------------------------------------------------------------------------------
End Meshing\n\n
"
#------------------------------------------------------------------------------


#------------------------------------------------------------------------------
echo -e "   - Restore 0 directory from 0.orig"
cp -r 0.orig 0 >> logFile
#------------------------------------------------------------------------------
echo -e "   - SetFields"
#setFields >>logFile
#decomposePar
